### ISSUE TITLE
AttributeError: 'list' object has no attribute 'fit'

### ISSUE THREAD

**Issue by zacstewart** [paulgb/sklearn-pandas#42]
I'm trying to transform one column with multiple transformers and I'm getting this error. My pipeline is as follows:

```python
model = Pipeline([
    ('mapper', DataFrameMapper([
        (['NAYear', 'NAHours'], None),
        (['Year'], [preprocessing.Imputer(), preprocessing.PolynomialFeatures()]),
        (['HoursMeter'], preprocessing.Imputer()),
        (['Manufacturer'], preprocessing.LabelBinarizer())
    ])),
    ('regression', linear_model.LinearRegression())
])
```

**Comment by zacstewart** [comment]
I was able to get around this by using another `Pipeline`.

```python
model = Pipeline([
    ('mapper', DataFrameMapper([
        (['NAYear', 'NAHours'], None),
        (['Year'], Pipeline([
            ('impute', preprocessing.Imputer()),
            ('polynomials', preprocessing.PolynomialFeatures())
        ])),
        (['HoursMeter'], preprocessing.Imputer()),
        (['Manufacturer'], preprocessing.LabelBinarizer())
    ])),
    ('regression', linear_model.LinearRegression())
])
```

In my opinion, this is even better than allowing the DataFrameMappter to take tuples with either a transformer or a list. It might be a little less ergonomic, but it means the interface is more consistent.

Maybe this just needs a README update?

**Comment by dukebody** [comment]
Hi zac!

The documentation examples you mention only work with the master, unreleased version of `sklearn-pandas`. The people with rights to make releases are probably not reading these issues at all.

I've written to @paulgb asking for write access to make a new release on PYPI.

In the meantime, you can workaround the issue installing the latest version directly from github or using a Pipeline as you do. 

Regarding the fact that of being preferable to use a sklearn Pipeline instead of passing a list of transformers, it's just a matter of syntax sugar. We copied parts of the code of the sklearn `Pipeline` for the list of transformers feature.

**Comment by zacstewart** [comment]
> Regarding the fact that of being preferable to use a sklearn Pipeline instead of passing a list of transformers, it's just a matter of syntax sugar. We copied parts of the code of the sklearn Pipeline for the list of transformers feature.

Cool. Why copy the code rather than just use `Pipeline` itself? If you did the latter, you might get to take advantage of any performance enhancements, etc… introduced to it.

**Comment by dukebody** [comment]
We have released a new version of sklearn-pandas to PYPI that supports the multiple transformers feature.

Regarding using `Pipeline` itself instead of copying part of the code, to be honest I don't rembember the rationale very well. Could you submit a PR that does this without breaking existing tests? Thanks!

**Comment by dukebody** [comment]
I'm closing this issue. @zacstewart see https://github.com/paulgb/sklearn-pandas/issues/43 regarding the direct use of `Pipeline` in `sklearn_pandas` code.
