### ISSUE TITLE
Test if we can use sklearn Pipeline instead of copying its code.

### ISSUE THREAD

**Issue by dukebody** [paulgb/sklearn-pandas#43]
For the multiple transformers as a list feature. See https://github.com/paulgb/sklearn-pandas/issues/42

**Comment by dukebody** [comment]
@zacstewart I'm now regretting from this... See https://github.com/paulgb/sklearn-pandas/issues/46 . sklearn `Pipeline` expects transformers with a `fit(x, y)` signature, `predict` method in the last one, etc. `sklearn-pandas` doesn't support this. I'm thinking perhaps we should get back to using custom code instead of the `Pipeline` code.

**Comment by dukebody** [comment]
I solved the mentioned issue subclassing `Pipeline`.

**Comment by zacstewart** [comment]
Nice fix, sorry I didn't consider this when I suggested we use `Pipeline`.

This touches on another limitation of run up against in sklearn. You can't put post-processors at the end of a pipeline. Sometimes I want to do something like `pred[pred < 0] = 0`, but because `Pipeline` expects every step to be a transformer, except the last one, which it expects to have `predict`.

I really wish we could just make `BaseEstimator` a subclass of `BaseTransformer`, and just use 'transform` instead of `predict`, or at least make them aliases. If you could just `fit` and `transform` all the way through the pipeline, it'd be a lot easier.

**Comment by dukebody** [comment]
Hmm I guess that you could code up some meta-estimator class that takes a pipeline and does some post-processing after the pipeline `predict`. Pseudo-code:

    class PostProcessor:
        def __init__(self, pipeline):
            self.pipeline = pipeline

        def fit(self, X, y=None, *args, **kwargs):
            return self.pipeline.fit(X, y, *args, **kwargs)

        def predict(self, X, *args, **kwargs):
            prediction = self.pipeline.predict(X, *args, **kwargs)
            prediction[prediction < 0] = 0
            return prediction

**Comment by zacstewart** [comment]
I was just rambling about `Pipeline`. Not looking for a fix in sklearn_pandas. I think that upstream in scikit-learn they should consider renaming `predict` to `transform`. Another use case is that I've sometimes wanted to put a bunch of estimators into a `FeatureUnion` as use them as features for a final estimator. To do that, [I basically wrap them with a `FeatureTransformer`](http://zacstewart.com/2014/08/05/pipelines-of-featureunions-of-pipelines.html).
